### ISSUE TITLE
Quality of life shortcuts

### ISSUE THREAD

**Issue by medv** [CSG4/super-graphiql#88]
Awesome package. At the moment, you have to tick and untick things in order to test queries in isolation. Traditional graphiql lets you just duplicate lots of tabs in your browser and fire queries/mutations separately. Could there be a shortcut in addition to CTRL+Enter that doesn't run everything that's ticked, but only the query/mutation that is currently selected by keyboard focus? Or a key modifier on the checkbox that when you hold, will untick all others and tick this one. 

This will essentially let me have 4-5 common things in one tab, and I can test them one by one (common things like CRUD require several operations in order to test fully). In order to do this, I still have to treat SuperGraphiql the same way as traditional Graphiql and open up lots of tabs, as the checkboxes are less convinient.

**Comment by angelascerbo** [comment]
Thanks for your support and interest in SuperGraphiQL. We appreciate your feedback to improve the UX and enhance your GraphQL workflow. We are working to implement this feature and will let you know when we release an update.
